package io.mosip.test.admintest.testcase;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.test.admintest.utility.BaseClass;
import io.mosip.test.admintest.utility.Commons;

public class DeviceTypesTest extends BaseClass{
 
  @Test(groups = "DT" )
  public void deviceTypesCRUD() {
	  String deviceTypes="admin/masterdata/device-types/view";
	  test=extent.createTest("DeviceTypesTest", "verify Login");
    Commons.click(test,driver,By.xpath("//a[@href='#/admin/masterdata']"));
   
    Commons.click(test,driver,By.id(deviceTypes));
    Commons.click(test,driver,By.id("Create"));
    test.log(Status.INFO, "Click on Create");
 

    Commons.enter(test,driver,By.id("code"),data);
    Commons.enter(test,driver,By.id("name"),data);
    Commons.enter(test,driver,By.id("description"),data);
  
    Commons.create(test,driver);
   	Commons.filter(test,driver, By.id("name"), data);
   	

   	Commons.edit(test,driver,data+1,By.id("name"));
   	test.log(Status.INFO, "Click on Edit");
   	Commons.filter(test,driver, By.id("name"), data+1);
   	
   	Commons.activate(test,driver);
   	test.log(Status.INFO, "Click on Active");
   	Commons.edit(test,driver,data+2,By.id("name"));
   	Commons.filter(test,driver, By.id("name"), data+2);
   	Commons.deactivate(test,driver);
   	test.log(Status.INFO, "Click on Deactive");
       }
   }
